version: "3.8"

services:
  neo4j:
    image: neo4j:latest
    container_name: neo4j-kgsearch
    environment:
      - NEO4J_AUTH=none
      - NEO4J_dbms_security_auth__enabled=false
    ports:
      - "7474:7474" # HTTP access to the Neo4j browser
      - "7687:7687" # Bolt protocol for application access

  app:
    build: .
    container_name: go-kgsearch
    depends_on:
      - neo4j
    environment:
      - NEO4J_URI=neo4j://neo4j:7687
    ports:
      - "8080:8080" # Expose the Go app's port
    command: ["./myapp"] # Ensure this matches the Go binary name
